TrajectoryPlannerROS:
  global_frame_id: "clober_0/odom"
  max_vel_x: 0.26
  min_vel_x: 0.1
  max_vel_theta: 1.82
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  meter_scoring : true

  controller_frequency: 10.0

