global_costmap:
  global_frame: map #The global frame for the costmap to operate in.
  robot_base_frame: clober_0/base_link #The name of the frame for the base link of the robot.

  transform_tolerance: 1.0 #Specifies the delay in transform (tf) data that is tolerable in seconds.
  update_frequency: 2.0 #The frequency in Hz for the map to be updated.
  publish_frequency: 2.0 #The frequency in Hz for the map to be publish display information.
  
  inflation_layer:
    inflation_radius: 0.2
    cost_scaling_factor: 10.0

  plugins: #Sequence of plugin specifications, one per layer.
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
