footprint: [[-0.15, 0.15], [-0.15, -0.15], [0.15, -0.15], [0.15, 0.15]]
# robot_radius: 0.3


inflation_layer:          
  inflation_radius : 1.0   #The radius in meters to which the map inflates obstacle cost values.
  cost_scaling_factor: 1.0 #A scaling factor to apply to cost values during inflation. 

obstacle_layer:
  observation_sources: laser_scan_sensor     #A list of observation source names separated by spaces. 
  laser_scan_sensor: {sensor_frame: clober_3/base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true, obstacle_range: 3.0, raytrace_range: 3.5,min_obstacle_height: 0.0, max_obstacle_height: 2.0}
  map_type: costmap
  track_unknown_space: true       #If false, each pixel has one of 2 states: lethal obstacle or free. If true, each pixel has one of 3 states: lethal obstacle, free, or unknown.


static_layer:
  unknown_cost_value: -1          #The value for which a cost should be considered unknown when reading in a map from the map server.
  lethal_cost_threshold: 100      #The threshold value at which to consider a cost lethal when reading in a map from the map server.
  map_topic: "map"
  first_map_only: false           #Only subscribe to the first message on the map topic, ignoring all subsequent messages
  subscribe_to_updates: true      #In addition to map_topic, also subscribe to map_topic + "_updates"
  track_unknown_space: true
  use_maximum: false              #Only matters if the static layer is not the bottom layer. 
  trinary_costmap: true           #If true, translates all map message values to NO_INFORMATION/FREE_SPACE/LETHAL_OBSTACLE (three values). If false, a full spectrum of intermediate values is possible.





